/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Company.Tools;

/**
 *
 * @author loai
 */
public class frmReports extends javax.swing.JFrame {

    /**
     * Creates new form frmReports
     */
    public frmReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDeptReports = new Rule.JButtonBox();
        btnBack = new Rule.JButtonBox();
        jButtonBox1 = new Rule.JButtonBox();
        jButtonBox2 = new Rule.JButtonBox();
        jButtonBox3 = new Rule.JButtonBox();
        jButtonBox4 = new Rule.JButtonBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reports");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 188, 28));

        btnDeptReports.setText("Deprtment Reports");
        btnDeptReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptReportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeptReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 265, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 359, 86, -1));

        jButtonBox1.setText("Employee Reports");
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 270, -1));

        jButtonBox2.setText("Project Reports");
        jButtonBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 270, -1));

        jButtonBox3.setText("WorkOnReports");
        jButtonBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 270, -1));

        jButtonBox4.setText("Phones Report");
        jButtonBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Tools.openForm(new MainScreen());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeptReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptReportsActionPerformed
        this.dispose();
        Tools.openForm(new frmReportDept());
    }//GEN-LAST:event_btnDeptReportsActionPerformed

    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
       this.dispose();
       Tools.openForm(new frmEmployeeReport());
    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void jButtonBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox2ActionPerformed
        Tools.openForm(new frmProjectReport());
    }//GEN-LAST:event_jButtonBox2ActionPerformed

    private void jButtonBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox3ActionPerformed
        this.dispose();
        Tools.openForm(new frmWorkOnReport());
    }//GEN-LAST:event_jButtonBox3ActionPerformed

    private void jButtonBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox4ActionPerformed
       this.dispose();
       Tools.openForm(new frmPhoneReport());
    }//GEN-LAST:event_jButtonBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Rule.JButtonBox btnBack;
    private Rule.JButtonBox btnDeptReports;
    private Rule.JButtonBox jButtonBox1;
    private Rule.JButtonBox jButtonBox2;
    private Rule.JButtonBox jButtonBox3;
    private Rule.JButtonBox jButtonBox4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
