/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Company.Tools;

/**
 *
 * @author loai
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBox1 = new Rule.JButtonBox();
        btnDepartment = new Rule.JButtonBox();
        jButtonBox6 = new Rule.JButtonBox();
        jButtonBox2 = new Rule.JButtonBox();
        jButtonBox3 = new Rule.JButtonBox();
        btnReports = new Rule.JButtonBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Main Screen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 178, 70));

        jButtonBox1.setText("Exit");
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 82, -1));

        btnDepartment.setText("Department");
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 250, -1));

        jButtonBox6.setText("Employee");
        jButtonBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, -1));

        jButtonBox2.setText("Project");
        jButtonBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, -1));

        jButtonBox3.setText("WorkOn");
        jButtonBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 250, -1));

        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
        Tools.openForm(new SC_Department());
        this.dispose();
    }//GEN-LAST:event_btnDepartmentActionPerformed

    private void jButtonBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox6ActionPerformed
        this.dispose();
        Tools.openForm(new SC_Employee());
    }//GEN-LAST:event_jButtonBox6ActionPerformed

    private void jButtonBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox3ActionPerformed
        this.dispose();
        Tools.openForm(new SC_WorkOn());
    }//GEN-LAST:event_jButtonBox3ActionPerformed

    private void jButtonBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox2ActionPerformed
       this.dispose();
        Tools.openForm(new frmProjectReport());
    }//GEN-LAST:event_jButtonBox2ActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
       this.dispose();
       Tools.openForm(new frmReports());
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Rule.JButtonBox btnDepartment;
    private Rule.JButtonBox btnReports;
    private Rule.JButtonBox jButtonBox1;
    private Rule.JButtonBox jButtonBox2;
    private Rule.JButtonBox jButtonBox3;
    private Rule.JButtonBox jButtonBox6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
