/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Company.Tools;
import java.sql.SQLException;
import structure.Department;


/**
 *
 * @author loai
 */
public class SC_Department extends javax.swing.JFrame {

    /**
     * Creates new form Department
     */
    public SC_Department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroub = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDeptNo = new Rule.JTextBox();
        txtDeptName = new Rule.JTextBox();
        txtDeptLocation = new Rule.JTextBox();
        btnAdd = new Rule.JButtonBox();
        btnUpdate = new Rule.JButtonBox();
        btnDelete = new Rule.JButtonBox();
        btnAll = new Rule.JButtonBox();
        btnFind = new Rule.JButtonBox();
        btnClear = new Rule.JButtonBox();
        btnBack = new Rule.JButtonBox();
        jLabel7 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        rdoLocation = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        txtSearch = new Rule.JTextBox();
        btnSearch = new Rule.JButtonBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDept = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Department");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 175, 71));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Search By");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 70, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Location:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 72, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Department Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 34));

        txtDeptNo.setEditable(false);
        getContentPane().add(txtDeptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 109, -1));
        getContentPane().add(txtDeptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 109, -1));
        getContentPane().add(txtDeptLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 109, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 386, 72, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 386, 76, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 386, 72, -1));

        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 386, 72, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 386, 72, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 386, 72, -1));

        btnBack.setText("Back To Main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 452, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 56, 34));

        rdoNumber.setBackground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("Number");
        getContentPane().add(rdoNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 123, -1, 30));

        rdoLocation.setBackground(new java.awt.Color(255, 255, 255));
        rdoLocation.setText("Location");
        getContentPane().add(rdoLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 123, -1, 30));

        rdoName.setBackground(new java.awt.Color(255, 255, 255));
        rdoName.setText("Name");
        getContentPane().add(rdoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 123, -1, 30));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 190, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 190, 80, -1));

        tblDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Number", "Name", "Location"
            }
        ));
        tblDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDept);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 319, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          btnGroub.add(rdoNumber);
          btnGroub.add(rdoName);
          btnGroub.add(rdoLocation);
          Clear();
          dept.getAllRows(tblDept);
          tblDept.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened
     Department dept = new Department();
        
      
    
    private void Clear(){
          Tools.clearText(this);
          txtDeptNo.setText(dept.AutoNum());
          btnAdd.setEnabled(true);
          btnUpdate.setEnabled(false);
          btnDelete.setEnabled(false);
          txtDeptName.requestFocus();
      }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.dispose();
        Tools.openForm(new MainScreen());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();       
    }//GEN-LAST:event_btnClearActionPerformed
  private void SetValue(){
        dept.setDeptName(txtDeptName.getText());
        dept.setLocation(txtDeptLocation.getText());
        dept.setDeptNo (Integer.parseInt(dept.AutoNum()));
  }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         dept.setDeptNo(Integer.parseInt(txtDeptNo.getText()));
        dept.setDeptName(txtDeptName.getText());
         dept.setLocation(txtDeptLocation.getText());
         dept.add();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
   
        dept.setDeptName(txtDeptName.getText());
        dept.setLocation(txtDeptLocation.getText());
        dept.setDeptNo (Integer.parseInt(dept.AutoNum()));
        dept.delete();
        Clear();
               dept.getAllRows(tblDept);


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    dept.setDeptNo(Integer.parseInt(txtDeptNo.getText()));
        dept.setDeptName(txtDeptName.getText());
         dept.setLocation(txtDeptLocation.getText());
         dept.update();
         dept.getAllRows(tblDept);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
       dept.getAllRows(tblDept);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
      String strDeptNO = (String)Tools.InputBox("Enter Department NO");
           int DeptNO =Integer.parseInt(strDeptNO);
           dept.setDeptNo(DeptNO);
           String s = "select * from department "+
                   " where DEPTNO= "+DeptNO;
           dept.getCustomRows(s, tblDept);
    }//GEN-LAST:event_btnFindActionPerformed

    private void tblDeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeptMouseClicked
       try{
        int val = tblDept.getSelectedRow();
        String strNo = tblDept.getValueAt(val, 0).toString();
        String strName = tblDept.getValueAt(val, 1).toString();
        String strLoc = tblDept.getValueAt(val, 2).toString();
        
        txtDeptNo.setText(strNo);
        txtDeptName.setText(strName);
        txtDeptLocation.setText(strLoc);
        
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
       }
       catch(Exception ex){
           Tools.msgBox(ex.getMessage());
       }
        
           
         
     
       
    }//GEN-LAST:event_tblDeptMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String s = "select * from department where ";
                   
        if(rdoNumber.isSelected()){
            s+="DEPTNO";
        
        }
       else if(rdoName.isSelected()){
            s+="DEPTNAME";
       
        }
        else {
            s+="LOCATION ";
        }
       s+=" like'%"+ txtSearch.getText()  +"%'";
       dept.getCustomRows(s, tblDept);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SC_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SC_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SC_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SC_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SC_Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Rule.JButtonBox btnAdd;
    private Rule.JButtonBox btnAll;
    private Rule.JButtonBox btnBack;
    private Rule.JButtonBox btnClear;
    private Rule.JButtonBox btnDelete;
    private Rule.JButtonBox btnFind;
    private javax.swing.ButtonGroup btnGroub;
    private Rule.JButtonBox btnSearch;
    private Rule.JButtonBox btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoLocation;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JTable tblDept;
    private javax.swing.JTextField txtDeptLocation;
    private javax.swing.JTextField txtDeptName;
    private javax.swing.JTextField txtDeptNo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
