/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Company.Tools;
import DataBase.conn;
import structure.Department;
import structure.Project;

/**
 *
 * @author loai
 */
public class SC_Project extends javax.swing.JFrame {

    /**
     * Creates new form SC_Project
     */
    public SC_Project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroub = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compDept = new Rule.JMyCompo();
        jLabel4 = new javax.swing.JLabel();
        txtLocation = new Rule.JTextBox();
        txtName = new Rule.JTextBox();
        txtNumber = new Rule.JTextBox();
        btnSearch = new Rule.JButtonBox();
        rdoNumber = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        rdoLocation = new javax.swing.JRadioButton();
        rdoDepartment = new javax.swing.JRadioButton();
        txtSearch = new Rule.JTextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProject = new javax.swing.JTable();
        btnAdd = new Rule.JButtonBox();
        btnUpdate = new Rule.JButtonBox();
        btnDelete = new Rule.JButtonBox();
        btnFind = new Rule.JButtonBox();
        btnAll = new Rule.JButtonBox();
        btnBack = new Rule.JButtonBox();
        btnClear = new Rule.JButtonBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonBox1 = new Rule.JButtonBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Project Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Project Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 89, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Location:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 89, 29));

        compDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compDeptActionPerformed(evt);
            }
        });
        getContentPane().add(compDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Departmect:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 80, 20));

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 20));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 20));

        txtNumber.setEditable(false);
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, 20));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 80, -1));

        rdoNumber.setBackground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("Number");
        getContentPane().add(rdoNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        rdoName.setBackground(new java.awt.Color(255, 255, 255));
        rdoName.setText("Name");
        getContentPane().add(rdoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 70, -1));

        rdoLocation.setBackground(new java.awt.Color(255, 255, 255));
        rdoLocation.setText("Location");
        getContentPane().add(rdoLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, -1, -1));

        rdoDepartment.setBackground(new java.awt.Color(255, 255, 255));
        rdoDepartment.setText("Department");
        getContentPane().add(rdoDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, -1, -1));

        txtSearch.setText("jTextBox4");
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 190, 180, -1));

        tblProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Project No", "Project Name", "Location", "Department No", "Department Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProject);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 470, 200));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 80, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 80, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 80, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, -1));

        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 80, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 80, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("PROJECT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 180, 40));

        jButtonBox1.setText("+");
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed
      Project p = new Project();

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGroub.add(rdoName);
        btnGroub.add(rdoNumber);
        btnGroub.add(rdoLocation);
        btnGroub.add(rdoDepartment);
        
        conn.fillCom("DEPARTMENT", "DEPTNAME", compDept);
        p.getAllRows(tblProject);
        
        Clear();
        tblProject.getTableHeader().setReorderingAllowed(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void compDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compDeptActionPerformed

    }//GEN-LAST:event_compDeptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     this.dispose();
     Tools.openForm(new MainScreen());
    }//GEN-LAST:event_btnBackActionPerformed
     public void Clear(){
         Tools.clearText(this);
         txtNumber.setText(p.AutoNum());
         txtName.requestFocus();
         btnAdd.setEnabled(true);
         btnDelete.setEnabled(false);
         btnUpdate.setEnabled(false);
          
        
     }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      Clear();
    }//GEN-LAST:event_btnClearActionPerformed
    Department d = new Department();
    public void set(){
        p.setProjectNo(Integer.parseInt(txtNumber.getText()));
        p.setProjectName(txtName.getText());
        p.setLocation(txtLocation.getText());
       
        
        String com = compDept.getSelectedItem().toString();
        String Valcom = d.getValueByName(com);
        p.setDeptNo(Integer.parseInt(Valcom));
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       set();
       p.add();
       Clear();
       p.getAllRows(tblProject);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String in = (String)Tools.InputBox("Enter Number Project");
           p.setProjectNo(Integer.parseInt(in));
           p.getOneRow(tblProject);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       set();
       p.update();
       Clear();
       p.getAllRows(tblProject);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectMouseClicked
       try{
            int row  = tblProject.getSelectedRow();
            
       String Pno = tblProject.getValueAt(row, 0).toString();
       String Pname = tblProject.getValueAt(row, 1).toString();
       String Loc = tblProject.getValueAt(row, 2).toString();
       
       String DeptN = tblProject.getValueAt(row, 3).toString();
       
       txtNumber.setText(Pno);
       txtName.setText(Pname);
       txtLocation.setText(Loc);
       compDept.setSelectedItem(DeptN);
      btnAdd.setEnabled(false);
      btnUpdate.setEnabled(true);
      btnDelete.setEnabled(true);
       }
       catch(Exception ex ){
           Tools.msgBox(ex.getMessage());
       }
    }//GEN-LAST:event_tblProjectMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       String s  = "select * from PROJECT_DATA "
               + " WHERE ";
       if(rdoNumber.isSelected()){
           s+=" PROJECT_NO ";
       }
       else if (rdoName.isSelected()){
            s+=" PROJECT ";
       }
       else if(rdoLocation.isSelected()){
           s+=" LOCATION ";
       }
       else{
           s+=" DEPARTMENT_NO ";
       }
       String str = s+=" like'%"+txtSearch.getText()+"%'";
       p.getCustomRows(str, tblProject);
    }//GEN-LAST:event_btnSearchActionPerformed
     
    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
               int Dno = Integer.parseInt(d.AutoNum());
               String Dname = (String)Tools.InputBox("Enter Department Name");
               String Loc = (String)Tools.InputBox("Enter Location");
               
               d.setDeptNo(Dno);
               d.setDeptName(Dname);
               d.setLocation(Loc);
               d.add();
               conn.fillCom("DEPARTMENT", "DEPTNAME", compDept);
    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
       p.getAllRows(tblProject);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        set();
        p.delete();
        Clear();
        p.getAllRows(tblProject);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SC_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SC_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SC_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SC_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SC_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Rule.JButtonBox btnAdd;
    private Rule.JButtonBox btnAll;
    private Rule.JButtonBox btnBack;
    private Rule.JButtonBox btnClear;
    private Rule.JButtonBox btnDelete;
    private Rule.JButtonBox btnFind;
    private javax.swing.ButtonGroup btnGroub;
    private Rule.JButtonBox btnSearch;
    private Rule.JButtonBox btnUpdate;
    private Rule.JMyCompo compDept;
    private Rule.JButtonBox jButtonBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoDepartment;
    private javax.swing.JRadioButton rdoLocation;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JTable tblProject;
    private Rule.JTextBox txtLocation;
    private Rule.JTextBox txtName;
    private Rule.JTextBox txtNumber;
    private Rule.JTextBox txtSearch;
    // End of variables declaration//GEN-END:variables
}
