/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Company.Tools;
import DataBase.conn;
import structure.Employee;
import structure.Project;
import structure.WorkOn;

/**
 *
 * @author loai
 */
public class SC_WorkOn extends javax.swing.JFrame {

    /**
     * Creates new form WorkOn
     */
    public SC_WorkOn() {
        initComponents();
    }
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroub1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pcom = new Rule.JMyCompo();
        Ecom = new Rule.JMyCompo();
        btnAdd = new Rule.JButtonBox();
        btnBack = new Rule.JButtonBox();
        btnDelete = new Rule.JButtonBox();
        btnFind = new Rule.JButtonBox();
        btnAll = new Rule.JButtonBox();
        jLabel4 = new javax.swing.JLabel();
        rdoENo = new javax.swing.JRadioButton();
        rdoPNo = new javax.swing.JRadioButton();
        rdoEName = new javax.swing.JRadioButton();
        rdoPName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblw = new javax.swing.JTable();
        jButtonBox1 = new Rule.JButtonBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Project:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("WORK ON");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Employee:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        getContentPane().add(Pcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, -1));
        getContentPane().add(Ecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, -1));

        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Search by:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 90, 30));

        rdoENo.setText("Employee No");
        rdoENo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoENoActionPerformed(evt);
            }
        });
        getContentPane().add(rdoENo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        rdoPNo.setText("Project No");
        getContentPane().add(rdoPNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        rdoEName.setText("Employee Name");
        getContentPane().add(rdoEName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        rdoPName.setText("Project Name");
        getContentPane().add(rdoPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        txtSearch.setText("jTextField1");
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 80, 260, 30));

        tblw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee No", "Emplyee Name", "Project No", "Project Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblwMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblw);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 370, 160));

        jButtonBox1.setText("Search");
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      this.dispose();
      Tools.openForm(new MainScreen());
    }//GEN-LAST:event_btnBackActionPerformed
   
    private void rdoENoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoENoActionPerformed
     
    }//GEN-LAST:event_rdoENoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btngroub1.add(rdoENo);
        btngroub1.add(rdoEName);
        btngroub1.add(rdoPName);
        btngroub1.add(rdoPNo);
        conn.fillCom("EMPLOYEE", "EMPNAME", Ecom);
        conn.fillCom("PROJECT", "PROJECTNAME", Pcom);
        w.getAllRows(tblw);
        tblw.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened
   WorkOn w = new WorkOn();
    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
           w.getAllRows(tblw);
    }//GEN-LAST:event_btnAllActionPerformed
  Employee e = new Employee();
  Project p = new Project();
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String pNo = (String)Tools.InputBox("Enter Project Number");
        String eNo = (String)Tools.InputBox("Enter Employee Number");
        w.setPROJECTNO(Integer.parseInt(eNo));
        w.setEMPNO(Integer.parseInt(eNo));
        String s = "select * from WORKON_DATA "
                +" where EMPLOYEE_NO= "+eNo+" and "+ "PROJECT_NO="+ pNo;
        conn.FillTable(s, tblw);
        
    }//GEN-LAST:event_btnFindActionPerformed
  private void setV(){
      String E = (String)Ecom.getSelectedItem();
      String P = (String)Pcom.getSelectedItem();
      
      String em = e.getValueByName(E);
      String Pr = p.getValueByName(P);
      w.setEMPNO(Integer.parseInt(em));
      w.setPROJECTNO(Integer.parseInt(Pr));
      
  }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
          setV();
          w.add();
          w.getAllRows(tblw);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
       String st= "select * from WORKON_DATA "
               +" WHERE ";
        if(rdoENo.isSelected()){
            st+="EMPLOYEE_NO  ";
        }
        else if(rdoEName.isSelected()){
            st+="EMPLOYEE_NAME ";
        }
        else if(rdoPNo.isSelected()){
            st+="PROJECT_NO  ";
        }
        else {
            st+="PROJECT_NAME  ";
        }
        st+=" like'%"+txtSearch.getText()+"%'"; 
        w.getCustomRows(st, tblw);
        
    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        setV();
        w.delete();
        w.getAllRows(tblw);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblwMouseClicked
        int row = tblw.getSelectedRow();
        String En = (String)tblw.getValueAt(row, 1);
        String Pn = (String)tblw.getValueAt(row, 3);
        
        Ecom.setSelectedItem(En);
        Pcom.setSelectedItem(Pn);
    }//GEN-LAST:event_tblwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SC_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SC_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SC_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SC_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Rule.JMyCompo Ecom;
    private Rule.JMyCompo Pcom;
    private Rule.JButtonBox btnAdd;
    private Rule.JButtonBox btnAll;
    private Rule.JButtonBox btnBack;
    private Rule.JButtonBox btnDelete;
    private Rule.JButtonBox btnFind;
    private javax.swing.ButtonGroup btngroub1;
    private Rule.JButtonBox jButtonBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoEName;
    private javax.swing.JRadioButton rdoENo;
    private javax.swing.JRadioButton rdoPName;
    private javax.swing.JRadioButton rdoPNo;
    private javax.swing.JTable tblw;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
